### ISSUE TITLE
How to add more users?

### ISSUE THREAD

**Issue by BobWs** [sashgorokhov/docker-nginx-webdav#7]
Hi,
How can I add more users? The --env is for only one user, but I need to add more users, is this possible?
TIA

**Comment by sashgorokhov** [comment]
Hello @BobWs.

This is possible, if you come up with the solution how to pass N pairs of credentials via env variables, and how to process them in entrypoint script. I am not going to do this myself, but your PR are welcome. If you are not going to do this yourself too, I am going to close this ticket.

Thanks!

**Comment by BobWs** [comment]
I'm sorry I don't know how to do that, that's why I ask you.
